language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: freebsd
    - os: osx
    - os: windows

addons:
  apt:
    packages:
      - cmake
  brew:
    packages:
      - cmake

before_script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS='-std=c++11'

script:
  - make
